### ISSUE TITLE
Set up workflow to automatically add issues to the project board

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-demos#12]
After failing with https://github.com/marketplace/actions/assign-to-one-project (maybe that's just for the old projects, not the new "projects (beta)"???), I'm now trying to set it up with the automation from here: https://github.com/community/community/discussions/5378

**Comment by jluethi** [comment]
This works now. 

For future reference:

## What is required?
1. Have a `.github/workflow/project-management.yml` file that contains the following:

```
name: Project automation

on:
  issues:
    types:
      - opened

jobs:
  add_issue_to_project:
    name: Add new issues to project board
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api graphql -f query='mutation($project:ID!, $issue:ID!) { addProjectNextItem(input: {projectId: $project, contentId: $issue}) { projectNextItem { id }  } }' -f project=${{ secrets.PROJECT_BOARD_ID }} -f issue=${{ github.event.issue.node_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
```

2. Have a github Personal access token in the repository that has the following permissions:
<img width="213" alt="Screenshot 2022-10-13 at 12 41 40" src="https://user-images.githubusercontent.com/18033446/195576108-f5abb578-b42a-4dd1-a2f4-4112b2a01268.png">
repo, workflow, write:org, read:org

It needs to be saved in settings; secrets; Actions => New repository secret as `MY_GITHUB_TOKEN`

3. Have the Project_Board_ID Node-ID set as a repository secret as well, i.e. `PROJECT_BOARD_ID` contains the node id.
To get the Node-ID, install github CLI, authenticate & do the following:
`gh api graphql -f query='query{ organization(login: "fractal-analytics-platform"){ projectNext(number: 1) { id } } }’`

This needs to be set up for each repo that should auto-add issues to the project board.
